default_context:
  project_name: 'wasletztepreis'
  project_slug: 'wasletztepreis'
  domain_main: 'wasletztepreis.net'
  domain_staging: 'stag.wasletztepreis.net'
  docker_swarm_stack_name_main: 'wasletztepreis-swarm'
  docker_swarm_stack_name_staging: 'stag-wasletztepreis-swarm'
  secret_key: 'a89387c0702ec4c0540c174a33406ba13cbb8df2c36688130fbd1b959dc578f2'
  first_superuser: 'admin@wasletztepreis.net'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.wasletztepreis.net", "https://stag.wasletztepreis.net", "https://wasletztepreis.net", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@wasletztepreis.net'
  postgres_password: 'P2kqWUHwMd'
  pgadmin_default_user: 'admin@wasletztepreis.net'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'wasletztepreis.net'
  traefik_constraint_tag_staging: 'stag.wasletztepreis.net'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
