"""Add Advert model

Revision ID: 8e19ca8c5d47
Revises: d4867f3a4c0a
Create Date: 2021-01-06 08:06:06.742322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e19ca8c5d47'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_advert_description'), 'advert', ['description'], unique=False)
    op.create_index(op.f('ix_advert_location'), 'advert', ['location'], unique=False)
    op.create_index(op.f('ix_advert_title'), 'advert', ['title'], unique=False)
    op.create_unique_constraint(None, 'item', ['id'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'item', type_='unique')
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.alter_column('item', 'owner_id',
               existing_type=sa.Integer(),
               type_=postgresql.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_advert_title'), table_name='advert')
    op.drop_index(op.f('ix_advert_location'), table_name='advert')
    op.drop_index(op.f('ix_advert_description'), table_name='advert')
    op.drop_table('advert')
    # ### end Alembic commands ###
